when:
  event:
    - push
    - manual
    - cron

variables:
  - &go_image "10.15.39.22:5000/ci-builder:latest"

steps:
  # lint:
  #   image: *go_image
  #   when:
  #     event: [push, manual, cron]
  #   commands:
  #     - go vet ./...

  # build:
  #   image: *go_image
  #   when:
  #     event: [push, manual, cron]
  #   commands:
  #     - go build ./...

  acceptance_test:
    image: *go_image
    when:
      event: [manual]
    environment:
      TF_ACC: "1"
      MSO_URL:
        from_secret: MSO_URL
      MSO_USERNAME:
        from_secret: MSO_USERNAME
      MSO_PASSWORD:
        from_secret: MSO_PASSWORD
      MSO_PLATFORM: "nd"
    commands:
      - echo "Running acceptance tests (regex ${ACC_TEST_REGEX:-${CI_BUILD_PARAM_ACC_TEST_REGEX:-${CI_PIPELINE_PARAM_ACC_TEST_REGEX:-^TestAccMSOSchemaTemplateBdResource$}}})"
      - go test ./mso/... -run "${ACC_TEST_REGEX:-${CI_BUILD_PARAM_ACC_TEST_REGEX:-${CI_PIPELINE_PARAM_ACC_TEST_REGEX:-^TestAccMSOSchemaTemplateBdResource$}}}" -count=1 -timeout 30m

labels:
  platform: linux/amd64