when:
  event:
    - push
    - manual
    - cron

variables:
  - &go_image "10.15.39.22:5000/ci-builder:latest"

steps:
  # lint:
  #   image: *go_image
  #   when:
  #     event: [push, manual, cron]
  #   commands:
  #     - go vet ./...

  # build:
  #   image: *go_image
  #   when:
  #     event: [push, manual, cron]
  #   commands:
  #     - go build ./...

  acceptance_test:
    image: *go_image
    when:
      event: [manual]
    environment:
      TF_ACC: "1"
      TF_LOG: ""
      MSO_PLATFORM: "nd"
      MSO_URL:
        from_secret: MSO_URL
      MSO_USERNAME:
        from_secret: MSO_USERNAME
      MSO_PASSWORD:
        from_secret: MSO_PASSWORD
      APIC_URL:
        from_secret: APIC_URL
      APIC_USERNAME:
        from_secret: APIC_USERNAME
      APIC_PASSWORD:
        from_secret: APIC_PASSWORD

    commands:
      - export ACC_TEST_REGEX="${ACC_TEST_REGEX:-${CI_BUILD_PARAM_ACC_TEST_REGEX:-${CI_PIPELINE_PARAM_ACC_TEST_REGEX:-^TestAccMSOSchemaTemplateBd.*}}}"
      - export ACC_TIMEOUT="${ACC_TIMEOUT:-${CI_BUILD_PARAM_ACC_TIMEOUT:-${CI_PIPELINE_PARAM_ACC_TIMEOUT:-600m}}}"
      - echo "Running acceptance tests (regex ${ACC_TEST_REGEX}, timeout ${ACC_TIMEOUT})"
      - go test -v ./mso/... -mod=vendor -run "${ACC_TEST_REGEX}" -count=1 -timeout "${ACC_TIMEOUT}"

labels:
  platform: linux/amd64